# Copyright 2009 Anders Fugmann.
# Distributed under the GNU General Public License v3
#
# This file is part of Borderline - A Firewall Generator
#
# Borderline is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Borderline is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Borderline.  If not, see <http://www.gnu.org/licenses/>.

CP=cp

.PHONY: autogen install tests

DESTDIR ?= .
export DESTDIR

PACKAGES = unix str num oUnit
BUILD_DIR = _build
BIN_DIR = $(DESTDIR)/bin
DOC_DIR = $(DESTDIR)/doc
TARGET = optimized
OCFLAGS = -annot -g
#-w @A
INCLUDE = src

SOURCES = $(wildcard src/*.ml src/*.mli src/*.mll src/*.mly) 

BINARIES = src/borderline \
	   src/bl_configure \
           src/unit_test

LEX_FILES = src/lexer.mll
YACC_FILES = src/parser.mly 

include makefile.mk

OCAMLRUNPARAM=b
export OCAMLRUNPARAM=b

.DEFAULT_GOAL := unittest

test: unittest 

unittest: install
	@$(BIN_DIR)/unit_test

install::  
	$(MAKE) -C configuration install
	[ -d $(DESTDIR)/etc/default/ ] || mkdir -p $(DESTDIR)/etc/default/
	[ -d $(DESTDIR)/etc/init.d/ ] || mkdir -p $(DESTDIR)/etc/init.d/
	@echo "MAIN=/etc/borderline/borderline.bl" > $(DESTDIR)/etc/default/borderline	
	@echo "DONT_START=1" >> $(DESTDIR)/etc/default/borderline	
	$(CP) borderline.sh $(DESTDIR)/etc/init.d/

#test: install
#	@$(MAKE) -C configuration autogenerated
#	@$(BIN_DIR)/bl_configure --force --output configuration/zones
#	@$(BIN_DIR)/borderline configuration/borderline.bl


/etc/default/borderline:
	@echo "MAIN=/etc/borderline/borderline.bl" > $@

distclean: clean
	$(RM) -fr $(DESTDIR)/etc/init.d/ $(DESTDIR)/etc/default/ $(DESTDIR)/etc/borderline

clean::
	@$(MAKE) -C configuration clean
	@$(RM) -fr *~

tests: install
	@cd tests; BORDERLINE=../$(BIN_DIR)/borderline ./test.sh
