CP=cp
.PHONY: autogen install

default: borderline autogen

autogen:
	$(MAKE) -C configuration autogenerated

borderline:
	$(MAKE) -C src main
	$(CP) -L src/main borderline

install: borderline autogen
	mkdir -p /etc/borderline /etc/borderline/zones /etc/borderline/generic
	$(CP) borderline /usr/local/sbin/
	$(CP) borderline.sh /etc/init.d/
	$(CP) configuration/main.bl /etc/borderline
	$(CP) -av configuration/zones/*.bl /etc/borderline/zones/
	$(CP) -av configuration/generic/*.bl /etc/borderline/generic/

clean:
	$(RM) -f borderline
	$(MAKE) -C configuration clean
	$(MAKE) -C src clean
