name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
      - name: Install dependencies
        run: sudo apt update && sudo apt install xsltproc nftables --yes

      - name: Opam dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Unittests
        run: opam exec -- dune runtest

      - name: Tests
        run: opam exec -- make test

      - name: E2E tests
        run: opam exec -- make integration
